### ISSUE TITLE
Twice as fast implementation of ampdLib

### ISSUE THREAD

**Issue by JeremyKarst** [LucaCerina/ampdLib#4]
Thank you very much for your ampdLib, I found it very useful in my tinkering.

I rewrote ampd in a way that reduces internal data duplication, and simplifies data structures. It seems to give me about a 2x improvement over ampd in my application, and without the problem splitting that ampdFast does. This implementation could also be used with ampdFast for even more speedup.

Because this version is more difficult to read and understand I would suggest providing this alongside the original if you decide to include it in ampdLib. Which one gets used by default is up to you.

And here it is, hope you find it helpful:

```
def ampd(inputSignal):
	np.seterr(divide='ignore', invalid='ignore')
	inputTime = np.arange(0, len(inputSignal))
	
	polyfit = np.polyfit(inputTime, inputSignal, 1)
	
	ds = (inputSignal - np.polyval(polyfit, inputTime)).astype(float)
	
	N = len(ds)
	L = int(np.ceil(N / 2.0)) - 1
	
	LSM = np.ones([L,N], dtype=int)
	
	for k in np.arange(1, L):
		LSM[k - 1, np.where((ds[k:N - k - 1] > ds[0: N - 2 * k - 1]) & (ds[k:N - k - 1] > ds[2 * k: N - 1]))[0]+k] = 0
		
	G = np.sum(LSM, 1)
	lm = np.where(G == G.min())[0][0]
	pks = np.where(np.sum(LSM[0:lm, :], 0)==0)[0]
	return pks
```

**Comment by LucaCerina** [comment]
Hello, sorry for the delay.
I tested your implementation and I agree on the performance improvement. I believe it is caused mainly by the usage of np.ones instead of np.uniform, but I made some tests and it doesn't seem to decrease the quality of the peak recognition.

I have added a test script to verify the performance improvements. You can prepare a pull request and add your authorship to the library, but I ask you a couple of things:
- Keep the comments in the code to guarantee readability and to let understand the flow
- Keep the original variable names (e.g. dtrSignal instead of ds) to guarantee readability
- We can use uint8 for the LSM dtype to furtherly reduce memory occupation.

Regarding ampdFast, it is required for long signals because LSM risks to saturate memory for large time windows. It needs some improvements to be sure that all peaks are identified correctly, but at the moment it works well.

**Comment by JeremyKarst** [comment]
I submitted a pull request. 

In addition to the previous changes it adds a new optional parameter LSM limit which I have found useful. This feature had also been requested in an earlier comment on adding a “maxWindow” to ampd. I included a thorough description on what it does and how to use it, but it is easily removed if you don’t want it.

**Comment by LucaCerina** [comment]
Merged.
Thank you for the code update.
